apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "stats-collector.fullname" . }}
  labels:
    {{- include "stats-collector.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "stats-collector.fullname" . }}
  labels:
    {{- include "stats-collector.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - pods
      - services
      - persistentvolumeclaims
      - persistentvolumes
      - namespaces
    verbs: ["get", "list"]
  - apiGroups: ["apps"]
    resources:
      - deployments
    verbs: ["get", "list"]
  - apiGroups: ["metrics.k8s.io"]
    resources:
      - nodes
      - pods
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "stats-collector.fullname" . }}
  labels:
    {{- include "stats-collector.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "stats-collector.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "stats-collector.fullname" . }}
    namespace: {{ .Release.Namespace }}
