apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stats-collector.fullname" . }}
  labels:
    {{- include "stats-collector.labels" . | nindent 4 }}
type: Opaque
stringData:
  STACKRADAR_URL: {{ .Values.stackradar.url | quote }}
  API_TOKEN: {{ .Values.stackradar.apiToken | quote }}
