apiVersion: v1
kind: Secret
metadata:
  name: {{ include "logpilot.fullname" . }}-secret
  labels:
    {{- include "logpilot.labels" . | nindent 4 }}
type: Opaque
data:
  jwt-secret: {{ .Values.config.jwtSecret | b64enc | quote }}
  admin-api-key: {{ .Values.config.adminApiKey | b64enc | quote }}
