apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "stackradar.fullname" . }}
  labels:
    {{- include "stackradar.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.certIssuer | quote }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
    - hosts:
        - {{ .Values.domain }}
      secretName: {{ include "stackradar.fullname" . }}-tls
  rules:
    - host: {{ .Values.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "stackradar.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
