{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stackradar.fullname" . }}
  labels:
    {{- include "stackradar.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  ADMIN_API_KEY: {{ .Values.secrets.adminApiKey | quote }}
  POSTGRES_PASSWORD: {{ .Values.database.password | quote }}
  ADMIN_PASSWORD: {{ .Values.admin.password | quote }}
  SITE_API_TOKEN: {{ .Values.secrets.siteApiToken | quote }}
{{- end }}
